swagger: '2.0'
info:
  description: 'An object with string to string mapping in a refed object'

definitions:

  RefObject:
    type: object
    required:
      - map
    properties:
      object_with_map:
        type: object
        additionalProperties:
          $ref: '#/definitions/MapStringToString'

  MapStringToString:
    type: object
    additionalProperties:
      type: string
